# Implements §9.4 EventBus contract.
extends Node

signal game_state_changed(from_state: int, to_state: int)
signal match_started(config: MatchConfig)
signal countdown_tick(seconds_left: int)
signal match_time_warning(kind: StringName)
signal match_ended(summary: MatchSummary)
signal pause_changed(paused: bool)
signal restart_requested()

signal character_spawned(id: int, pos: Vector2, initial: bool)
signal respawn_scheduled(id: int, seconds: float)
signal character_damaged(ev: DamageEvent)
signal character_killed(ev: KillEvent)
signal stealth_started(id: int, duration: float)
signal stealth_ended(id: int)
signal jetpack_state_changed(id: int, active: bool, burnout: bool)
signal character_landed(id: int, speed: float, surface: int)
signal updraft_entered(id: int)
signal footstep(id: int, surface: int)

signal weapon_fired(shooter_id: int, weapon_id: StringName, muzzle: Vector2, dir: Vector2)
signal weapon_reload_started(id: int, weapon_id: StringName, duration: float)
signal weapon_reload_finished(id: int, weapon_id: StringName)
signal weapon_empty_click(id: int, weapon_id: StringName)
signal weapon_switched(id: int, from_id: StringName, to_id: StringName)
signal weapon_picked_up(id: int, weapon_id: StringName, socket_id: StringName)
signal weapon_dropped(id: int, weapon_id: StringName, pos: Vector2)
signal frag_pack_collected(id: int, amount: int)

signal projectile_impact(kind: int, pos: Vector2, normal: Vector2, surface: int, weapon_id: StringName, hit_character: bool, headshot: bool)
signal projectile_bounced(kind: int, pos: Vector2, normal: Vector2, speed: float)
signal near_miss(target_id: int, pos: Vector2, speed: float)
signal beam_state_changed(shooter_id: int, active: bool)
signal flame_state_changed(shooter_id: int, active: bool)
signal grenade_thrown(id: int, pos: Vector2, vel: Vector2)
signal grenade_bounced(pos: Vector2, speed: float)
signal explosion(ev: ExplosionEvent)

signal socket_item_spawned(socket_id: StringName, item_id: StringName)
signal socket_item_taken(socket_id: StringName, by_id: int)
signal rocket_boost_spawned(socket_id: StringName, pos: Vector2)
signal rocket_boost_collected(by_id: int, duration: float)
signal rocket_boost_expired(id: int)
signal rocket_boost_despawned(socket_id: StringName)

signal director_phase_changed(phase: int, intensity: float)
signal bot_token_changed(bot_id: int, has_token: bool)
signal bot_state_changed(bot_id: int, state: int)
signal settings_changed(section: StringName)
signal keybinding_changed(action: StringName)
signal toast_requested(text: String, style: StringName, seconds: float)
